package insults

func GetInsult() []string {

	listInsults := []string{
		"Accapareur",
		"Aérolithe",
		"Amiral de bateau-lavoir",
		"Amphitryon",
		"Anacoluthe",
		"Analphabète",
		"Analphabète diplômé",
		"Animal",
		"Anthracite",
		"Anthropophage",
		"Anthropopithèque",
		"Apache",
		"Apophtegme",
		"Apprenti-dictateur à la noix de coco",
		"Arlequin",
		"Ascenseur",
		"Astronaute d'eau douce",
		"Athlète complet",
		"Autocrate",
		"Autodidacte",
		"Aztèques",
		"Babouin",
		"Bachi-bouzouk",
		"Bachi-bouzouk de tonnerre de Brest",
		"Bachi-bouzouk des Carpathes",
		"Bande de jeunes effrontés",
		"Bande de joyeux drilles",
		"Bande d'ectoplasmes de tonnerre de Brest",
		"Bande d'tres",
		"Bande d'enragés",
		"Bande d'escrocs",
		"Bande d'hurluberlus",
		"Bande de bachi-bouzouks",
		"Bande de brutes",
		"Bande de canaques",
		"Bande de Ku-Klux-Klans",
		"Bande de pirates",
		"Bande de sauvages",
		"Bande de voleurs",
		"Bande de zapotèques de tonnerre de Brest",
		"Bandit",
		"Bayadère de carnaval",
		"Bibelot",
		"Bibendum",
		"Bidule",
		"Blague fumisterie et compagnie",
		"Boit-sans-soif",
		"Bombe atomique",
		"Bon sang",
		"Bonhomme",
		"Bougre d'ectoplasme à roulettes",
		"Bougre d'ectoplasme de moule à gaufres",
		"Bougre d'amiral de bateau-lavoir",
		"Bougre de crème d'tre à la graisse de hérisson",
		"Bougre d'extrait de cornichon",
		"Bougre d'extrait de crétin des Alpes",
		"Bougre d'extrait d'hydrocarbure",
		"Bougres de faux jetons à la sauce tartare",
		"Bougre de méchant Blanc",
		"Bougre de mouchard",
		"Bougre d'olibrius",
		"Bougre d'ostrogoth",
		"Bougre de papou des Carpathes",
		"Bougre de petit cornichon",
		"Bougre de phénomène de tonnerre de Brest",
		"Bougre de phénomène de moule à gaufres de tonnerre de Brest",
		"Bougre de sauvage d'aérolithe de tonnerre de Brest",
		"Bougre de zouave",
		"Bougres de zouaves d'anthropopithèques",
		"Brigand",
		"Brontosaure",
		"Brute",
		"Bulldozer à réaction",
		"Cachalot",
		"Cake-walk",
		"Calembredaine",
		"Canaille",
		"Canaque",
		"Cannibale",
		"Cannibale emplumé",
		"Capitaine de bateau-lavoir",
		"Casse-pieds",
		"Catachrèse",
		"Cataplasme",
		"Cercopythèque",
		"Cercueil volant",
		"Chauffard",
		"Chenapan",
		"Cher petit ami",
		"Choléra",
		"Chouette mal empaillée",
		"Chrysanthème",
		"Cigare volant",
		"Cloche à fromage",
		"Cloporte",
		"Clown",
		"Clysopompe",
		"Coléoptère",
		"Coloquinte",
		"Coloquinte à la graisse de hérisson",
		"Concentré de moules à gaufres",
		"Coquin",
		"Cornemuse",
		"Cornichon",
		"Cornichon de zouave de tonnerre de Brest",
		"Cornichon diplômé",
		"Corsaire",
		"Coup de Trafalgar",
		"Coupe-jarret",
		"Cow-boy de la route",
		"Crème d'tre à la graisse de hérisson",
		"Crétin de l'tré à la graisse de hérisson",
		"Empoisonneur",
		"Encordé",
		"Énergumène",
		"Enfer et damnation",
		"Enfonceur de porte ouverte",
		"Enragé",
		"Entêté",
		"Épouvantail",
		"Équilibriste",
		"Esclavagiste",
		"Escogriffe",
		"Escroc",
		"Espèce de loup-garou à la graisse de renoncule de mille sabords",
		"Espèce de porc-épic mal embouché",
		"Extrait d'che",
		"Gredin",
		"Grenouille",
		"Gros-plein-de-soupe",
		"Grotesque polichinelle",
		"Gyroscope",
		"Hérétique",
		"Hors-la-loi",
		"Hurluberlu",
		"Hydrocarbure",
		"Iconoclaste",
		"[[Empire inca|Inca]] de carnaval",
		"Individu de général de tonnerre de Brest",
		"Invertébré",
		"Isotope",
		"Ivrogne",
		"Jet d'che",
		"Lascar",
		"Lépidoptère",
		"Logarithme",
		"Loup-garou à la graisse de renoncule de mille tonnerres de Brest",
		"Maboul",
		"Macaque",
		"Macrocéphale",
		"Malappris",
		"Malheureux",
		"Malotru",
		"Mamelouk",
		"Marchand de guano",
		"Marchand de tapis",
		"Marin d'eau douce",
		"Marmotte male réveillée",
		"Mazette",
		"Mégacycle",
		"Mégalomane",
		"Mercanti",
		"Mercenaire",
		"Mérinos",
		"Mérinos mal peignés",
		"Migou de malheur",
		"Mille milliards de mille millions de mille sabords",
		"Mille milliards de mille sabords",
		"Mille milliards de mille sabords de tonnerre de Brest",
		"Mille milliards de tonnerre de Brest",
		"Mille millions de mille milliards de mille sabords",
		"Mille millions de mille milliards de mille sabords de tonnerre de Brest",
		"Mille millions de mille sabords",
		"Mille millions de mille sabords de tonnerre de Brest",
		"Mille millions de sabords",
		"Mille millions de tonnerre de Brest",
		"Mille sabords",
		"Mille tonnerres",
		"Mille tonnerres de Brest",
		"Misérable",
		"Misérable ectoplasme",
		"Misérable ver-de-terre",
		"Mitrailleur à bavette",
		"Moratorium",
		"Moricaud",
		"Morues dans un carton à chapeau",
		"Mouchard",
		"Moujik",
		"Moule à gaufres",
		"Moussaillon",
		"Moussaillon de malheur",
		"Moussaillon du diable",
		"Mufle",
		"MRKRPXZKRMTFRZ",
		"Mussolini de carnaval",
		"Naufrageur",
		"Négrier",
		"Noix de coco",
		"Nom d'une pipe",
		"Nyctalope",
		"Olibrius",
		"Ophicléide",
		"Ornithorynque",
		"Oryctérope",
		"Ostrogoth",
		"Ours mal léché",
		"Pachyderme",
		"Pacte à quatre",
		"Paltoquet",
		"Pantoufle",
		"Papou",
		"Papou des Carpathes",
		"Paranoïaques",
		"Parasites",
		"Patagon",
		"Patagon de Zoulou",
		"Patapouf",
		"Patate",
		"Pauvre bougre",
		"Pauvre type",
		"Peau-rouge",
		"Pénultième",
		"Père volant",
		"Péronnelle",
		"Perruche bavarde",
		"Perroquet déplumé",
		"Petit choléra",
		"Petit délicat",
		"Petit ornithorynque",
		"Petite tigresse",
		"Petit vaurien",
		"Phénomène",
		"Phlébotome",
		"Phylactère",
		"Phylloxéra",
		"Pignouf",
		"Pirate",
		"Pirate d'eau douce",
		"Pirate du ciel",
		"Plein de dos",
		"Pleurnichard",
		"Polichinelle",
		"Polygraphe",
		"Porc-épic mal embouché",
		"Potentat",
		"Poussière",
		"Profiteur",
		"Projectile guidé",
		"Protozoaire",
		"Pyromane",
		"Pyrophore",
		"Que diable",
		"Que le grand cric me croque et me fasse avaler ma barbe",
		"Rapace",
		"Rat",
		"Ravachol",
		"Renégat",
		"Rhizopode",
		"Rocaille de tonnerre de Brest",
		"Rocambole",
		"Sacré mitrailleur à bavette",
		"Sacripant",
		"Sajou",
		"Sale bête",
		"Saleté d'appareil à sous",
		"Sale vilaine bête de tonnerre de Brest",
		"Saltimbanque",
		"Sapajou",
		"Sapristi",
		"Satanée fusée de tonnerre de Brest",
		"Satanée marche",
		"Satanée fenêtre",
		"Satrape",
		"Sauvage",
		"Sauvage d'aérolithe",
		"Scaphandrier d'eau de vaisselle",
		"Scélérat",
		"Schizophrène",
		"Scolopendre",
		"Scorpion",
		"Serpent",
		"Simili-Martien à la graisse de cabestan",
		"Sinapisme",
		"Sinistre farceur",
		"Sombre brute",
		"Sombre oryctérope",
		"Soulographe",
		"Sous-produit d'ectoplasme",
		"Tas de cornichons",
		"Tas de sauvages",
		"Tchouk-tchouk-nougat",
		"Technocrate",
		"Terroriste",
		"Tête de lard",
		"Tête de mule",
		"Têtu comme un mule",
		"Tigresse",
		"Tonnerre",
		"Tonnerre de Brest",
		"Tonnerre de tonnerre de Brest",
		"Topinambour",
		"Tortionnaire",
		"Trafiquant de chair humaine",
		"Traeau ambulant",
		"Jeune chenapan",
		"Jeune impertinent",
		"Jocrisse",
		"Judas",
		"Jus de réglisse",
		"Khroumir",
		"Ku Klux Klan",
		"Kanak",
		"Lhydrocarbure",
		"Extrait de cornichon",
		"Face de brute",
		"Farceur",
		"Fatma de prisunic",
		"Faux frère",
		"Faux jeton",
		"Faux jeton à la sauce tartare",
		"Fichue espagnolette",
		"Fichue fusée de tonnerre de Brest",
		"Fieffé menteur",
		"Fiston",
		"Flibustier",
		"Flibustier de carnaval",
		"Flte",
		"Forban",
		"Fourbe",
		"Frère de la côte",
		"Froussard",
		"Gaillard",
		"Galopin",
		"Gamin",
		"Gangster",
		"Garde-côtes à la mie de pain",
		"Gargarisme",
		"Garnement",
		"Gibier de potence",
		"Goujat",
		"Graine de vaurien",
		"Graisse de hérisson",
		"Graisse de trombone à coulisse",
		"Grand escogriffe",
		"Grand ltre",
		"Empl'ne-potence",
		"Tratre",
		"Tricheur",
		"Troglodyte",
		"Trompe-la-mort",
		"Troufignol",
		"Vampire",
		"Vandale",
		"Va-nu-pieds",
		"Vaurien",
		"Végétarien",
		"Ver-de-terre",
		"Vercingétorix de carnaval",
		"Vermicelles",
		"Vermine",
		"Vieille baderne",
		"Vieille branche",
		"Vieille coque rouillée",
		"Vieille marmotte",
		"Vieille perruche bavarde",
		"Vieux farceur",
		"Vieux frère",
		"Vieux rafiot que je suis",
		"Vipère",
		"Vivisectionniste",
		"Volatile de malheur",
		"Voleur",
		"Voleur d'enfants",
		"Wisigoths",
		"Zapothèques",
		"Zèbre",
		"Zigomar",
		"Zouave",
		"Zouave interplanétaire",
		"Zouave à la noix de coco",
		"ZoulouHimalaya",
		"Crétin des Alpes",
		"Crétin des Balkans",
		"Commerce noir",
		"Cromagnon",
		"Cuistre",
		"Cyanure",
		"Cyclone",
		"Cyclone ambulant",
		"Cyclotron",
		"Cyrano à quatre pattes",
		"Diable",
		"Diable de zouave",
		"Diablesse",
		"Dieu soit loué",
		"Diplodocus",
		"Doryphore",
		"Doux agneaux",
		"Dynamiteur",
		"Ecornifleur",
		"Écraseur",
		"Ectoplasme",
		"Ectoplasme à roulettes",
		"Égoïste",
		"Électron",
		"Ectoplasme",
		"Ectoplasme à roulettes",
	}
	return listInsults
}
